import { POPULAR_EMOJI_ENTRIES, type EmojiSearchEntry } from './emojiSearch';

const entry = (emoji: string, name: string, keywords: string): EmojiSearchEntry => ({ emoji, name, keywords });

/** Full named collection, loaded when someone searches or opens See all. */
export const EMOJI_SEARCH_ENTRIES: readonly EmojiSearchEntry[] = [
  POPULAR_EMOJI_ENTRIES[0]!,
  entry('😄', 'Grinning face with smiling eyes', 'happy smile laugh joyful'),
  entry('😁', 'Beaming face with smiling eyes', 'happy grin teeth smile'),
  POPULAR_EMOJI_ENTRIES[1]!,
  entry('🤣', 'Rolling on the floor laughing', 'rofl lol funny tears'),
  entry('😊', 'Smiling face with smiling eyes', 'happy blush shy sweet'),
  entry('😇', 'Smiling face with halo', 'angel innocent good'),
  entry('🙂', 'Slightly smiling face', 'smile happy okay'),
  entry('😉', 'Winking face', 'wink playful flirt'),
  POPULAR_EMOJI_ENTRIES[2]!,
  entry('😘', 'Face blowing a kiss', 'love heart kiss'),
  entry('😜', 'Winking face with tongue', 'silly playful crazy'),
  entry('🤪', 'Zany face', 'silly wild crazy goofy'),
  entry('😝', 'Squinting face with tongue', 'silly playful laugh'),
  entry('🤑', 'Money mouth face', 'rich cash dollar money'),
  entry('🤗', 'Smiling face with open hands', 'hug hugging welcome'),
  entry('🤭', 'Face with hand over mouth', 'oops giggle shy surprise'),
  entry('🤫', 'Shushing face', 'quiet silence secret hush'),
  POPULAR_EMOJI_ENTRIES[5]!,
  entry('😐', 'Neutral face', 'meh blank expressionless'),
  entry('😑', 'Expressionless face', 'meh annoyed blank'),
  entry('😶', 'Face without mouth', 'speechless silent quiet'),
  entry('😏', 'Smirking face', 'smirk smug flirt'),
  entry('😒', 'Unamused face', 'annoyed bored side eye'),
  entry('🙄', 'Face with rolling eyes', 'eyeroll annoyed whatever'),
  entry('😬', 'Grimacing face', 'awkward nervous teeth cringe'),
  entry('😌', 'Relieved face', 'calm peace content relaxed'),
  entry('😔', 'Pensive face', 'sad sorry disappointed'),
  entry('😪', 'Sleepy face', 'tired sleep'),
  entry('🤤', 'Drooling face', 'hungry delicious desire'),
  entry('😴', 'Sleeping face', 'sleep tired snooze zzz'),
  entry('😷', 'Face with medical mask', 'sick illness health'),
  entry('🤒', 'Face with thermometer', 'sick fever illness'),
  entry('🤕', 'Face with head bandage', 'hurt injured sick'),
  entry('🤢', 'Nauseated face', 'sick green disgust nausea'),
  entry('🤮', 'Face vomiting', 'sick puke disgust'),
  entry('🥴', 'Woozy face', 'dizzy tipsy drunk'),
  entry('😵', 'Face with crossed out eyes', 'dizzy dead shocked'),
  POPULAR_EMOJI_ENTRIES[8]!,
  entry('🤠', 'Cowboy hat face', 'western yeehaw hat'),
  POPULAR_EMOJI_ENTRIES[3]!,
  POPULAR_EMOJI_ENTRIES[4]!,
  entry('🤓', 'Nerd face', 'glasses smart geek'),
  entry('🧐', 'Face with monocle', 'inspect curious suspicious'),
  entry('😕', 'Confused face', 'confusion unsure puzzled'),
  entry('😟', 'Worried face', 'worry nervous concerned'),
  entry('🙁', 'Slightly frowning face', 'sad frown unhappy'),
  entry('😮', 'Face with open mouth', 'surprise wow shocked'),
  entry('😯', 'Hushed face', 'surprise quiet stunned'),
  entry('😲', 'Astonished face', 'surprise amazed wow'),
  entry('😳', 'Flushed face', 'blush embarrassed surprise'),
  POPULAR_EMOJI_ENTRIES[6]!,
  entry('😦', 'Frowning face with open mouth', 'sad shocked concern'),
  entry('😨', 'Fearful face', 'scared fear afraid'),
  entry('😰', 'Anxious face with sweat', 'nervous worried stress'),
  entry('😥', 'Sad but relieved face', 'sad sweat disappointed'),
  entry('😢', 'Crying face', 'sad cry tear'),
  POPULAR_EMOJI_ENTRIES[7]!,
  entry('😱', 'Face screaming in fear', 'scared scream horror shocked'),
  entry('😖', 'Confounded face', 'frustrated upset pain'),
  entry('😣', 'Persevering face', 'struggle frustrated pain'),
  entry('😞', 'Disappointed face', 'sad regret unhappy'),
  entry('😓', 'Downcast face with sweat', 'sad stress tired'),
  entry('😩', 'Weary face', 'tired exhausted frustrated'),
  entry('😫', 'Tired face', 'exhausted frustrated weary'),
  entry('🥱', 'Yawning face', 'sleepy tired bored'),
  entry('😤', 'Face with steam from nose', 'angry frustrated triumph'),
  entry('😡', 'Enraged face', 'angry mad rage red'),
  entry('😠', 'Angry face', 'mad annoyed upset'),
  entry('🤬', 'Face with symbols on mouth', 'angry swearing curse censored'),
  entry('💀', 'Skull', 'dead death skeleton halloween'),
  entry('☠️', 'Skull and crossbones', 'pirate danger poison death'),
  entry('💩', 'Pile of poo', 'poop funny stink'),
  entry('🤡', 'Clown face', 'circus funny clown'),
  entry('👹', 'Ogre', 'monster demon japanese oni'),
  entry('👺', 'Goblin', 'monster demon japanese tengu'),
  POPULAR_EMOJI_ENTRIES[9]!,
  entry('👽', 'Alien', 'space extraterrestrial ufo'),
  entry('🤖', 'Robot', 'bot technology machine'),
  entry('🎃', 'Jack o lantern', 'pumpkin halloween spooky'),
  POPULAR_EMOJI_ENTRIES[10]!,
  entry('👎', 'Thumbs down', 'no bad dislike disapprove'),
  entry('👏', 'Clapping hands', 'applause bravo congrats'),
  entry('🙌', 'Raising hands', 'hooray celebrate praise'),
  entry('🙏', 'Folded hands', 'pray thanks please gratitude'),
  entry('💪', 'Flexed biceps', 'strong strength muscle workout'),
  entry('🤝', 'Handshake', 'deal agreement friends partnership'),
  entry('✌️', 'Victory hand', 'peace two fingers'),
  entry('🤞', 'Crossed fingers', 'luck hope wish'),
  POPULAR_EMOJI_ENTRIES[11]!,
  POPULAR_EMOJI_ENTRIES[12]!,
  entry('🧡', 'Orange heart', 'love warm'),
  entry('💛', 'Yellow heart', 'love friendship sunshine'),
  entry('💚', 'Green heart', 'love nature'),
  entry('💙', 'Blue heart', 'love trust'),
  entry('💜', 'Purple heart', 'love violet'),
  entry('🖤', 'Black heart', 'love dark'),
  entry('🤍', 'White heart', 'love pure'),
  entry('💔', 'Broken heart', 'sad heartbreak love'),
  entry('💕', 'Two hearts', 'love affection pink'),
  POPULAR_EMOJI_ENTRIES[13]!,
  entry('⭐', 'Star', 'favorite rating gold'),
  entry('🌟', 'Glowing star', 'shine brilliant gold'),
  POPULAR_EMOJI_ENTRIES[14]!,
  entry('💥', 'Collision', 'boom explosion impact'),
  entry('💯', 'Hundred points', 'perfect score real agree'),
  entry('✅', 'Check mark button', 'yes done success approved'),
  entry('❌', 'Cross mark', 'no wrong cancel error'),
  POPULAR_EMOJI_ENTRIES[15]!,
  entry('🎁', 'Wrapped gift', 'present birthday surprise'),
  entry('🎂', 'Birthday cake', 'celebrate candle dessert'),
  entry('🏆', 'Trophy', 'winner award champion'),
  entry('🚀', 'Rocket', 'launch space fast'),
  entry('💡', 'Light bulb', 'idea bright inspiration'),
  entry('🌈', 'Rainbow', 'color pride weather'),
  entry('☀️', 'Sun', 'sunny summer weather bright'),
  entry('🌙', 'Crescent moon', 'night sleep sky'),
  entry('🌸', 'Cherry blossom', 'flower pink spring'),
  entry('🌻', 'Sunflower', 'flower yellow summer'),
  entry('🌹', 'Rose', 'flower red love romance'),
  entry('🍀', 'Four leaf clover', 'luck lucky green'),
  entry('🐶', 'Dog face', 'puppy pet animal'),
  POPULAR_EMOJI_ENTRIES[16]!,
  entry('🐸', 'Frog', 'green toad animal'),
  entry('🐻', 'Bear', 'teddy animal'),
  entry('🐼', 'Panda', 'bear animal cute'),
  entry('🦊', 'Fox', 'animal orange'),
  entry('🦄', 'Unicorn', 'magic horse rainbow'),
  entry('🦋', 'Butterfly', 'insect blue nature'),
  entry('🐝', 'Honeybee', 'bee insect honey'),
  POPULAR_EMOJI_ENTRIES[17]!,
  entry('🍔', 'Hamburger', 'burger food lunch'),
  entry('🍟', 'French fries', 'food potato chips'),
  entry('🌮', 'Taco', 'food mexican'),
  entry('🍩', 'Doughnut', 'donut dessert food sweet'),
  entry('☕', 'Hot beverage', 'coffee tea drink caffeine'),
  entry('🍺', 'Beer mug', 'drink cheers pub'),
  entry('⚽', 'Soccer ball', 'football sport'),
  entry('🏀', 'Basketball', 'ball sport'),
  entry('🎮', 'Video game', 'gaming controller play'),
  entry('🎵', 'Musical note', 'music song sound'),
  entry('👑', 'Crown', 'king queen royalty'),
];
